module.exports = {
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,

    FIREBASE_API_KEY_DEV: process.env.FIREBASE_API_KEY_DEV,
    FIREBASE_AUTH_DOMAIN_DEV: process.env.FIREBASE_AUTH_DOMAIN_DEV,
    FIREBASE_DATABASE_URL_DEV: process.env.FIREBASE_DATABASE_URL_DEV,
    FIREBASE_PROJECT_ID_DEV: process.env.FIREBASE_PROJECT_ID_DEV,
    FIREBASE_STORAGE_BUCKET_DEV: process.env.FIREBASE_STORAGE_BUCKET_DEV,
    FIREBASE_MESSAGING_SENDER_ID_DEV:
      process.env.FIREBASE_MESSAGING_SENDER_ID_DEV,
    FIREBASE_APP_ID_DEV: process.env.FIREBASE_APP_ID_DEV
  }
};
