name: Prod hosting

on: 
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Firebase GitHub Action
          uses: pizzafox/firebase-action@1.0.7
          env:
            PROJECT_ID: "earn-dog"
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_PROD_TOKEN }}
          with:
            args: deploy
