name: Prod hosting

on: 
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  install_build_and_test:
    name: Install, Build and Test the app first...

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm test
      env:
        CI: true

  deploy:
    name: Deploy the app to Production
    needs: install_build_and_test
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_PROD_TOKEN }}
  
